version: '3.7'

services:

  angular-frontend:
    container_name: frontend-portal
    build:
      context: .
      dockerfile: Dockerfile-Devl
    ports:
      - '80:80'
    environment:
      - NODE_ENV=devl